title: "Kartikey Saini | Data Analyst & BI Specialist"  # Website Title
logo: "/images/Capture.PNG?raw=true"  # Path to Your Logo/Image


  Data-driven analyst with 4+ years of experience in data analysis and operational workflows, leveraging SQL, Python, Power BI, Excel, and Machine Learning to drive business insights and process efficiency. 
  Passionate about transforming raw data into actionable intelligence, optimizing decision-making, and automating workflows for improved accuracy and performance. 
  Continuously exploring innovative data science applications to enhance business impact.

links:
  - name: LinkedIn
    url: "https://www.linkedin.com/in/kartikey-saini-268827144"
  - name: GitHub
    url: "https://github.com/kartikeysaini98"

